on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          # Add your build commands here

  test:
    name: 'Test'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: |
          # Add your test commands here

  uat:
    name: 'UAT'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: UAT Test
        run: |
          # Add your UAT test commands here

  deploy:
    name: 'Deploy'
    needs: uat
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
      - name: ServiceNow Change
        uses: ServiceNow/servicenow-devops-change@v4.0.0
        with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'Deploy'
          change-request: |
            {
              "attributes": {
                "requested_by": {"name": "DevOps System"},
                "cmdb_ci": {"name": "ServiceNow Corpsite"},
                "business_service": {"name": "ServiceNow Corpsite Service"},
                "assignment_group": {"name": "DevOps Connect"},
                "assigned_to": {"name": "Hrijula Bose"},
                "priority": "2",
                "comments": "This is a sample pipeline script to be added in your change step",
                "work_notes": "Update this to work_notes",
                "u_mitigation_for_operational_impact": "Back change out",
                "u_time_for_mitigation_to_complete": "Less than 15 minutes",
                "u_mitigation_is_successfully_tested": "Yes",
                "u_validation_type": "Technical validation only"
              }
            }
